---

- import_tasks: checks.yml
  tags: [kubeapps]

- include_tasks: internal-acme.yml

- include_tasks: manifests.yml
  tags: [kubeapps]
  when: item.condition | default(true)
  args: { apply: { tags: [kubeapps] } }
  loop:
    - src: core-dns-config-crd.yml
      condition: "{{ kubeapps_ingress_controller_ip is defined }}"
    - { src: cert-manager-chart-crd.yml, deploy:  "{{ cert_manager_namespace }}" }
    - src: trust-manager-chart-crd.yml
      deploy: trust-manager 
      ns: "{{ cert_manager_namespace }}"
      condition: "{{ cert_manager_is_internal }}"
    - src: trust-bundle-config-crd.yml
      condition: "{{ cert_manager_is_internal }}"
    - { src: dex-chart-crd.yml , deploy: "{{ dex_namespace }}" }
    - src: kubeapps-chart-crd.yml
      deploy: "{{ kubeapps_namespace }}"
